apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki-prod:3100
    isDefault: false
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "correlationId=([a-f0-9-]+)"
          name: CorrelationId
          url: "$${__value.raw}"
        - datasourceUid: tempo
          matcherRegex: "runId=([a-f0-9-]+)"
          name: RunId
          url: "$${__value.raw}"
