{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "atlasia.fullname" . }}-orchestrator
  labels:
    {{- include "atlasia.orchestrator.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "atlasia.orchestrator.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "atlasia.fullname" . }}-frontend
  labels:
    {{- include "atlasia.frontend.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "atlasia.frontend.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
    - to:
        - podSelector:
            matchLabels:
              {{- include "atlasia.orchestrator.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.orchestrator.service.port }}
{{- end }}
