{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "atlasia.fullname" . }}-orchestrator
  labels:
    {{- include "atlasia.orchestrator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "atlasia.orchestrator.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
    scrapeTimeout: 10s
{{- end }}
